apiVersion: v1
kind: Namespace
metadata:
  name: kube-news
  labels:
    name: kube-news
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: kube-news
  labels:
    app: kube-news
type: Opaque
data:
  host: cG9zdGdyZXMtc2VydmljZS5uYW1lc3BhY2Uuc3ZjLmNsdXN0ZXIubG9jYWw=
  username: a3ViZWRld25ld3M=
  password: UGcjMTIz
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-news
  namespace: kube-news
  labels:
    app: kube-news
